stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  only:
    - main
  script:
    - make
    - pwd
    - sudo mv -f build/logservice /opt/app/logserver/bin/logservice
    - sudo mv -f build/logconsumer /opt/app/logserver/bin/logconsumer
    - sudo sv restart logserver
