stages:
  - build
  - deploy-test
  - deploy-prod

variables:
  ARTIFACT_DIR: "/opt/artifacts"
  DEPLOY_SERVICE: "/opt/deploy/deploy"
  GROUP: "logserver"
  SERVICE: "logservice"
  CONSUMER: "logconsumer"
  KEEP_VERSIONS: 5

default:
  before_script:
    - VERSION=$(git rev-parse --short HEAD)

unit-test:
  stage: .pre
  tags:
    - unit
  script:
    - make test

build:
  stage: build
  tags:
    - txm-build
  only:
    - main
    - test
  script:
    - if [ ! -d $ARTIFACT_DIR ]; then mkdir -p $ARTIFACT_DIR; fi;
    - make
    - mv -f build/$SERVICE $ARTIFACT_DIR/$SERVICE.v_$VERSION
    - mv -f build/$CONSUMER $ARTIFACT_DIR/$CONSUMER.v_$VERSION

deploy-test:
  stage: deploy-test
  tags:
    - txm-build
  only:
    - test
  script:
    - sudo $DEPLOY_SERVICE -r -e test -g $GROUP -s $SERVICE -v $VERSION -a $ARTIFACT_DIR/$SERVICE.v_$VERSION -k $KEEP_VERSIONS
    - sudo $DEPLOY_SERVICE -r -e test -g $GROUP -s $CONSUMER -v $VERSION -a $ARTIFACT_DIR/$CONSUMER.v_$VERSION -k $KEEP_VERSIONS

deploy-prod:
  stage: deploy-prod
  tags:
    - txm-build
  only:
    - main
  script:
    - sudo $DEPLOY_SERVICE -r -e prod -g $GROUP -s $SERVICE -v $VERSION -a $ARTIFACT_DIR/$SERVICE.v_$VERSION -k $KEEP_VERSIONS
    - sudo $DEPLOY_SERVICE -e prod -g $GROUP -s $CONSUMER -v $VERSION -a $ARTIFACT_DIR/$CONSUMER.v_$VERSION -k $KEEP_VERSIONS
