stages:
  - build
  - deploy-test
  - deploy-prod

variables:
  ARTIFACT_DIR: "/opt/artifacts"
  DEPLOY_SERVICE: "/opt/deploy/deploy"
  GROUP: "logserver"
  SERVICE: "logservice"
  CONSUMER: "logconsumer"
  KEEP_VERSIONS: 5

default:
  before_script:
    - if [ ! -d $ARTIFACT_DIR ]; then mkdir -p $ARTIFACT_DIR; fi;
    - VERSION=$(git rev-parse --short HEAD)
    - VERSION_DATE=$($(MAKEFILE_PATH)/commit_date.sh '%m%d%H%M')
    - SERVICE_OUTPUT=$ARTIFACT_DIR/$SERVICE.$VERSION_DATE.v_$VERSION
    - CONSUMER_OUTPUT=$ARTIFACT_DIR/$CONSUMER.$VERSION_DATE.v_$VERSION

unit-test:
  stage: .pre
  tags:
    - unit
  script:
    - make test

build:
  stage: build
  tags:
    - txm-build
  only:
    - main
    - test
  script:
    - make
    - mv -f build/$SERVICE $SERVICE_OUTPUT
    - mv -f build/$CONSUMER $CONSUMER_OUTPUT

deploy-test:
  stage: deploy-test
  tags:
    - txm-build
  only:
    - test
  script:
    - sudo $DEPLOY_SERVICE -r -e test -g $GROUP -s $SERVICE -v $VERSION -a $SERVICE_OUTPUT -k $KEEP_VERSIONS
    - sudo $DEPLOY_SERVICE -r -e test -g $GROUP -s $CONSUMER -v $VERSION -a $CONSUMER_OUTPUT -k $KEEP_VERSIONS

deploy-prod:
  stage: deploy-prod
  tags:
    - txm-build
  only:
    - main
  script:
    - sudo $DEPLOY_SERVICE -r -e prod -g $GROUP -s $SERVICE -v $VERSION -a $SERVICE_OUTPUT -k $KEEP_VERSIONS
    - sudo $DEPLOY_SERVICE -e prod -g $GROUP -s $CONSUMER -v $VERSION -a $CONSUMER_OUTPUT -k $KEEP_VERSIONS
